"""Generate hamr_data.py from the original JS sources (js/compress.js, js/alphabets.js).

The JS dictionary literals are JSON-compatible (quoted keys/values), so we can
parse them with json.loads and preserve JS insertion order exactly.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).parent
compress_js = (ROOT / "js" / "compress.js").read_text(encoding="utf-8")
alphabets_js = (ROOT / "js" / "alphabets.js").read_text(encoding="utf-8")


def extract_js_object(source: str, name: str) -> str:
    """Return the raw {...} literal assigned to `const name = {...};`."""
    m = re.search(rf"const {name} = (\{{.*?\}});", source, re.S)
    if not m:
        raise SystemExit(f"object {name} not found")
    return m.group(1)


def extract_js_array(source: str, name: str) -> list:
    # Form 1: "....".split("")  (single-char alphabet; string may contain ';')
    m = re.search(rf'export const {name} = ("(?:[^"\\]|\\.)*")\.split\(""\);', source, re.S)
    if m:
        return list(json.loads(m.group(1)))
    # Form 2: [...] array literal (emoji sequences; none contain ']')
    m = re.search(rf"export const {name} = (\[.*?\]);", source, re.S)
    if m:
        return json.loads(m.group(1))
    raise SystemExit(f"array {name} not found")


tld_encode = json.loads(extract_js_object(compress_js, "tldEncode"))
sld_encode = json.loads(extract_js_object(compress_js, "sldEncode"))
domain_encode = json.loads(extract_js_object(compress_js, "domainEncode"))
path_encode = json.loads(extract_js_object(compress_js, "pathEncode"))

alpha_ascii = extract_js_array(alphabets_js, "outputAlphabetASCII")
alpha_qr = extract_js_array(alphabets_js, "outputAlphabetQR")
alpha_emoji = extract_js_array(alphabets_js, "outputAlphabetEmoji")

# Sanity checks mirroring invariants the algorithm relies on.
assert "" in tld_encode, "tldEncode[''] must exist (fallback TLD code)"
assert len(alpha_ascii) == len(set(alpha_ascii))
assert len(alpha_qr) == len(set(alpha_qr))
assert len(alpha_emoji) == len(set(alpha_emoji))

out = ROOT / "hamr_data.py"
with out.open("w", encoding="utf-8") as f:
    f.write('"""Huffman dictionaries and output alphabets from the original ha.mr\n')
    f.write("sources (compress.js / alphabets.js). Auto-generated by build_data.py -\n")
    f.write('do not edit by hand. Dict order matches JS object insertion order.\n"""\n\n')
    f.write(f"VERSION = 0\n\n")
    f.write(f"TLD_ENCODE = {json.dumps(tld_encode, ensure_ascii=False)}\n\n")
    f.write(f"SLD_ENCODE = {json.dumps(sld_encode, ensure_ascii=False)}\n\n")
    f.write(f"DOMAIN_ENCODE = {json.dumps(domain_encode, ensure_ascii=False)}\n\n")
    f.write(f"PATH_ENCODE = {json.dumps(path_encode, ensure_ascii=False)}\n\n")
    f.write(f"OUTPUT_ALPHABET_ASCII = {json.dumps(alpha_ascii, ensure_ascii=False)}\n\n")
    f.write(f"OUTPUT_ALPHABET_QR = {json.dumps(alpha_qr, ensure_ascii=False)}\n\n")
    f.write(f"OUTPUT_ALPHABET_EMOJI = {json.dumps(alpha_emoji, ensure_ascii=False)}\n")

print(f"tldEncode: {len(tld_encode)} entries")
print(f"sldEncode: {len(sld_encode)} entries")
print(f"domainEncode: {len(domain_encode)} entries")
print(f"pathEncode: {len(path_encode)} entries")
print(f"alphabets: ascii={len(alpha_ascii)} qr={len(alpha_qr)} emoji={len(alpha_emoji)}")
print(f"written: {out} ({out.stat().st_size} bytes)")
